name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project johnydev

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

      - name: Run OPA policy checks
        run: |
          wget https://openpolicyagent.org/downloads/latest/opa_linux_amd64 -O opa
          chmod +x opa
          ./opa eval --fail-defined \
            -i firewall.tf \
            -d policies \
            'data.main.deny' \
            --format pretty

      - name: Terraform Init and Validate
        run: |
          terraform init
          terraform validate
